download:
  class_path: lhotse.recipes.librispeech.download_librispeech
  init_args:
    dataset_parts: mini_librispeech
    target_dir: export/data/mini_librispeech
prepare:
  class_path: lhotse.recipes.librispeech.prepare_librispeech
  init_args:
    corpus_dir: export/data/mini_librispeech/LibriSpeech