# pytorch_lightning==2.5.1
seed_everything: true
model:
  class_path: models.asr.dummy.models.dnn_manual.Dnn
  init_args:
    input_dim: 40
    hidden_dim: 100
    output_dim: 40
data:
  class_path: sequential.data.lhotse_datamodule.LhotseRecipesDataModule
  init_args:
    download:
      class_path: lhotse.recipes.librispeech.download_librispeech
      init_args:
        dataset_parts: mini_librispeech
        target_dir: export/data/mini_librispeech
    prepare:
      class_path: lhotse.recipes.librispeech.prepare_librispeech
      init_args:
        corpus_dir: export/data/mini_librispeech/LibriSpeech

    train_manifest: train-clean-5
    train_dataset:
      class_path: sequential.data.dataset.K2SpeechRecognitionDatasetWraper
      init_args: 
        input_strategy:
          class_path: lhotse.dataset.input_strategies.OnTheFlyFeatures
          init_args:
            extractor:
              class_path: lhotse.features.kaldi.extractors.Fbank
              init_args:
                config:
                  num_mel_bins: 40
    train_sampler:
      class_path: lhotse.dataset.sampling.simple.SimpleCutSampler
      init_args:
        max_duration: 200
        shuffle: True


trainer:
  default_root_dir: dnn_npu
  max_epochs: 2
  logger: true
  accelerator: 
    class_path: lightning_npu.accelerators.npu.NPUAccelerator
  devices: 8
  num_nodes: 1
  strategy: 
    class_path: lightning_npu.strategies.npu_deepspeed.NPUDeepSpeedStrategy
    init_args:
      config: models/asr/dummy/configs/ds_config.json
  use_distributed_sampler: false

