# pytorch_lightning==2.5.1
seed_everything: true
model:
  class_path: models.asr.dummy.models.dnn.Dnn
  init_args:
    input_dim: 100
    hidden_dim: 100
    output_dim: 100
data:
  class_path: data.lhotse_recipes_datamodule.LhotseRecipesDataModule
  init_args:
    recipe_config: models/asr/dummy/configs/timit.yaml
    train_params:
      manifest_part: train
      dataset:
        class_path: data.dataset.K2SpeechRecognitionDatasetWraper
        init_args: 
          input_strategy:
            class_path: lhotse.dataset.input_strategies.AudioSamples
            init_args:
              sampling_rate: 16000
              mono: True
      sampler:
        class_path: lhotse.dataset.sampling.SimpleCutSampler
        init_args:
          max_duration: 200
          shuffle: True
      dataloader:
        class_path: torch.utils.data.DataLoader
        init_args:
          num_workers: 1


trainer:
  max_epochs: 10
  logger: true

