# pytorch_lightning==2.5.1
seed_everything: true
model:
  class_path: models.asr.fireredasr.models.fireredasr_llm.FireRedAsrLlm
  init_args:
    encoder:
      class_path: models.asr.fireredasr.models.module.conformer_encoder.ConformerEncoder
      init_args:
        idim: 80
        n_layers: 16
        n_head: 20
        d_model: 1280
        residual_dropout: 0.1
        dropout_rate: 0.1
        kernel_size: 33
        pe_maxlen: 5000

    llm:
      class_path: sequential.utils.builder.auto_model_for_causal_lm_from_pretrained_wrapper
      init_args:
        pretrained_model_name_or_path: models/asr/fireredasr/pretrained_model/FireRedASR/FireRedASR-LLM-L/Qwen2-7B-Instruct
      dict_kwargs:
        attn_implementation: eager # flash_attention_2
        # torch_dtype: torch.float32 # torch.float16

    tokenizer:
      class_path: models.asr.fireredasr.tokenizer.llm_tokenizer.build_llm_tokenizer
      init_args:
        llm_path: models/asr/fireredasr/pretrained_model/FireRedASR/FireRedASR-LLM-L/Qwen2-7B-Instruct

    encoder_projector:
      class_path: models.asr.fireredasr.models.module.adapter.Adapter
      init_args:
        encoder_dim: 1280
        llm_dim: 3584
        downsample_rate: 2


    feat_extractor:
      class_path: models.asr.fireredasr.data.asr_feat.ASRFeatExtractor
      init_args:
        kaldi_cmvn_file: models/asr/fireredasr/pretrained_model/FireRedASR/FireRedASR-LLM-L/cmvn.ark

    freeze_encoder: true
    freeze_llm: true
    use_lora: true

data:
  class_path: sequential.data.lhotse_datamodule.LhotseManifestDataModule
  init_args:
    train_manifest_dir: export/aispeech/asr/collectionzh+en+fangyan-2w-asr/dev/
    train_dataset:
      class_path: sequential.data.dataset.K2SpeechRecognitionDatasetWraper
      init_args:
        input_strategy:
          class_path: lhotse.dataset.input_strategies.OnTheFlyFeatures
          init_args:
            extractor:
              class_path: lhotse.features.kaldi.extractors.Fbank
              init_args:
                config:
                  num_mel_bins: 80
    train_sampler:
      class_path: lhotse.dataset.sampling.SimpleCutSampler
      init_args:
        max_duration: 200
        shuffle: True
    audio_backend:
      class_path: sequential.data.audio_backend.KaldiAudioBackend

trainer:
  default_root_dir: fireredasr_npu
  max_epochs: 2
  logger: true
  accelerator:
    class_path: lightning_npu.accelerators.npu.NPUAccelerator
  devices: 1
  strategy:
    class_path: lightning_npu.strategies.npu.SingleNPUStrategy
  use_distributed_sampler: false

